### ISSUE TITLE
ソースコードにTABが含まれていると、コンパイルエラー"error: invalid charactor; '\t'になる

### ISSUE THREAD

**Issue by ykominami** [toppers/asp3_in_zig#13]
$ zig build-exe hello_with_tab.zig
.\hello_with_tab.zig:5:1: error: invalid character: '\t'
        try stdout.print("Hello, {}!\n", .{"world"});

$ zig version
0.6.0+d139e44cf

linux用、macos用、windows用のzigコンパイルで確認しました。

以下のURLのZigのDocumentationの最初にあるhello.zigにTABを追加して、エラーになることを確認しました。
また、TABを追加しなければ、エラーにならないことも確認しました。

https://ziglang.org/documentation/master/

Zigの制限なのかもしれませんが、上記URLではそのことの言及はありませんでした。
注意喚起という意図でissueとしてこちらに、書きました。

**Comment by hiroakitakada** [comment]
Zigでは，ソースコード中にTABを入れることができません。どこかに書いてあったと思うのですが…

asp3_in_zigの問題点ではないので，クローズさせていただきます。
